abbr = {
	"-acron-": "Acronimo / Abbreviazione",
	"-agg form-": "Aggettivo, forma flessa",
	"-agg nom-": "Aggettivo nominale",
	"-agg num form-": "Aggettivo numerale, forma flessa",
	"-agg num-": "Aggettivo numerale",
	"-agg-": "Aggettivo",
	"-alter-":"Alterati",
	"-ant-":"Contrari",
	"-art-": "Articolo",
	"-avv-": "Avverbio",
	"-card-": "Cardinale",
	"-carhi-": "Carattere Hiragana",
	"-class-": "Classificatore",
	"-cifr-": "Cifra",
	"-cod-": "Codice / Simbolo",
	"-conf-": "Confisso",
	"-cong-": "Congiunzione",
	"-der-":"Derivate",
	"-espress-": "Espressione",
	"-etim-":"Etimologia",
	"-hanzi-": "Caratteri cinesi Hanzi",
	"-inter-": "Interiezione ",
	"-iperon-":"Iperonimi",
	"-ipon-":"Iponimi",
	"-kanji-": "Kanji",
	"-kanpr-": "Pronuncia Kanji",
	"-lett-": "Lettera",
	"-loc agg-": "Locuzione aggettivale",
	"-loc avv-": "Locuzione avverbiale",
	"-loc cong-": "Locuzione congiuntiva",
	"-loc inter-": "Locuzione interiettiva",
	"-loc nom form-": "Locuzione nominale, forma flessa",
	"-loc nom-": "Locuzione nominale",
	"-loc prep-": "Locuzione prepositiva",
	"-loc verb-": "Locuzione verbale",
	"-noconf-":"da non confondere", 
	"-nome form-": "Nome proprio, forma flessa",
	"-nome-": "Nome proprio",
	"-num-": "Aggettivo numerale",
	"-ord-": "Ordinale",
	"-part-": "Particella",
	"-posp-": "Posposizione",
	"-pref-": "Prefisso",
	"-prep-": "Preposizione",
	"-pron form-": "Pronome, forma flessa ",
	"-pron poss-": "Pronome possessivo",
	"-pronome-": "Pronome",
	"-prov-":"Proverbi, Modi di dire",
	"-rel-":"Termini Correlati",
	"-sin-":"Sinonimi",
	"-uso-":"Uso",
	"-chat-":"Altro",
	"-sost form-": "Sostantivo, forma flessa",
	"-sost-": "Sostantivo",
	"-suff-": "Suffisso",
	"-trascrizione-": "Trascrizione",
	"-var-":"Varianti",
	"-verb form-": "Voce verbale",
	"-verb-": "Verbo",
	"Accr": "(accrescitivo)",
	"Dim":"(diminutivo)",
	"Est": "(per estensione)",
	"Fig": "(senso figurato)",
	"Lett":"(letteralmente)",
	"Mig": "(migliorativo)",
	"Pegg": "(peggiorativo)",
	"Spreg": "(spregiativo)",
	"Vezz": "(vezzeggiativo)",
}