
lang = {
    "np": "lingua sconosciuta",
    "aa": "afar",
    "aaa": "ghotuo",
    "ab": "abcaso",
    "abs": "malese ambonese",
    "ace": "accinese",
    "ach": "acioli",
    "ada": "adangme",
    "ady": "adighè",
    "ae": "avestico",
    "af": "afrikaans",
    "afh": "afrihili",
    "agf": "arguni",
    "aie": "amara",
    "ain": "ainu",
    "aka": "akan",
    "akg": "anakalangu",
    "akk": "accado",
    "akz": "alabama",
    "ale": "aleuto",
    "alp": "alune",
    "als": "albanese tosco",
    "alt": "altai meridionale",
    "am": "amarico",
    "amb": "ambai",
    "an": "aragonese",
    "ang": "anglosassone",
    "apa": "apache",
    "apm": "mescalero-chiricahua",
    "aqc": "arcio",
    "ar": "arabo",
    "arc": "aramaico",
    "arn": "mapudungun",
    "arp": "arapaho",
    "ars": "arabo najdi",
    "art": "novial",
    "arw": "aruaco",
    "as": "assamese",
    "ast": "asturiano",
    "aua": "asumboa",
    "aud": "lingua anuta",
    "aut": "lingua australe",
    "ava": "avaro",
    "ave": "avestico",
    "avk": "kotava",
    "awa": "awadhi",
    "ay": "aymara",
    "az": "azero",
    "ba": "baschiro",
    "baa": "babatana",
    "bad": "banda",
    "bal": "beluci",
    "bam": "bambara",
    "ban": "balinese",
    "bar": "bavarese",
    "bas": "basa",
    "bbc": "batak toba",
    "bcl": "bicolano centrale",
    "bcm": "bannoni",
    "bdg": "bonggi",
    "be": "bielorusso",
    "bej": "begia",
    "bem": "bemba",
    "ber": "berbero",
    "bg": "bulgaro",
    "bh": "bihari",
    "bho": "bhojpuri",
    "bhp": "bima",
    "bhw": "biak",
    "bi": "bislama",
    "bin": "bini",
    "bjn": "banjar",
    "bla": "blackfoot",
    "blg": "balau",
    "bm": "bambara",
    "bn": "bengalese",
    "bnq": "bantik",
    "bo": "tibetano",
    "br": "bretone",
    "bra": "braj",
    "bs": "bosniaco",
    "bty": "bobot",
    "bug": "buginese",
    "bvk": "bukat",
    "bwd": "bwaidoka",
    "bzg": "babuza",
    "bzq": "buli",
    "ca": "catalano",
    "cad": "caddo",
    "cal": "caroliniano",
    "car": "caraibico",
    "ce": "ceceno",
    "ceb": "cebuano",
    "ch": "chamorro",
    "chb": "chibcha",
    "che": "ceceno",
    "chg": "ciagataico",
    "chk": "chuukese",
    "chm": "mari",
    "chn": "chinook",
    "cho": "choctaw",
    "chr": "cherokee",
    "chv": "ciuvasce",
    "chy": "cheyenne",
    "cic": "chickasaw",
    "ckb": "curdo centrale",
    "cmn": "cinese mandarino",
    "co": "corso",
    "cop": "copto",
    "cr": "cree",
    "cre": "cree",
    "crh": "tataro di Crimea",
    "cro": "crow",
    "cs": "ceco",
    "csb": "casciubico",
    "cu": "antico slavo ecclesiastico",
    "cv": "ciuvascio",
    "cy": "gallese",
    "da": "danese",
    "dak": "dakota",
    "de": "tedesco",
    "del": "delaware",
    "der": "lingua deori",
    "de-at": "austriaco",
    "dhv": "drehu",
    "dim": "dime",
    "din": "dinca",
    "diq": "dimli",
    "dlm": "dalmatico",
    "dob": "dobu",
    "doi": "dogri",
    "dsb": "lusaziano inferiore",
    "dua": "duala",
    "dum": "olandese medio",
    "dv": "divehi",
    "dyu": "diula",
    "dz": "bhutanese",
    "ee": "ewe",
    "efi": "efik",
    "egy": "egiziano",
    "el": "greco",
    "el-it" : "griko salentino",
    "elx": "elamitico",
    "emb": "embaloh",
    "eml": "emiliano-romagnolo",
    "en": "inglese",
    "en-uk" : "inglese britannico",
    "en-us": "inglese americano",
    "eo": "esperanto",
    "es": "spagnolo",
    "es-ar": "spagnolo argentino",
    "eso": "ekspreso",
    "et": "estone",
    "etr": "edolo",
    "ett": "etrusco",
    "eu": "basco",
    "evn": "evenki",
    "ewe": "ewe",
    "ewo": "ewondo",
    "fa": "persiano",
    "fan": "fan",
    "fat": "fanti",
    "fi": "finlandese",
    "fil": "filippino",
    "fiu": "ugrofinnica",
    "fj": "figiano",
    "fo": "faroese",
    "fr": "francese",
    "frr": "frisone settentrionale",
    "frm": "francese medio",
    "fro": "francese antico",
    "fur": "friulano",
    "fy": "frisone",
    "ga": "irlandese",
    "gag": "gagauzo",
    "gay": "gayo",
    "gan": "gan",
    "gd": "gaelico scozzese",
    "gdd": "gedaged",
    "gei": "geber",
    "ges": "geser-gorom",
    "gil": "gilbertese",
    "gl": "galiziano",
    "gmh": "alto tedesco medio",
    "gn": "guaranì",
    "goh": "alto tedesco antico",
    "gon": "gondi",
    "gor": "gorontalo",
    "got": "gotico",
    "grb": "grebo",
    "grc": "greco antico",
    "gri": "ghari",
    "gsw": "svizzero tedesco",
    "gu": "gujarati",
    "gv": "mannese",
    "gzn": "gane",
    "ha": "hausa",
    "hak": "lingua hakka",
    "hai": "haida",
    "haw": "hawaiano",
    "he": "ebraico",
    "her": "herero",
    "hi": "hindi",
    "hil": "hiligayna",
    "him": "himachali",
    "hmo": "hiri motu",
    "hnn": "hanunoo",
    "hoa": "hoava",
    "hop": "hopi",
    "hr": "croato",
    "hrx": "hunsrik",
    "hsb": "lusaziano superiore",
    "ht": "creolo haitiano",
    "htu": "hitu",
    "hu": "ungherese",
    "hup": "hupa",
    "hus": "huasteco",
    "hy": "armeno",
    "ia": "interlingua",
    "iba": "iban",
    "ibg": "ibanag",
    "ibo": "igbo",
    "id": "indonesiano",
    "ie": "interlingue",
    "ijo": "ijo",
    "ilo": "ilocano",
    "ilu":"ili'uun",
    "imr": "imroing",
    "ins": "insubre",
    "int": "lingua unificata",
    "io": "ido",
    "irh": "irarutu",
    "is": "islandese",
    "it": "italiano",
    "iu": "inuktitut",
    "ja": "giapponese",
    "ja-ka": "giapponese kana",
    "ja-ro": "giapponese rōmaji",
    "jam": "creolo giamaicano",
    "jbo": "lojban",
    "jpr": "giudeo-persiano",
    "jrb": "giudeo-arabo",
    "jv": "giavanese",
    "ka": "georgiano",
    "kaa": " karakalpaka",
    "kab": "lingua cabila",
    "kac": "kachin",
    "kam": "kamba",
    "kar": "karen",
    "kau": "kanuri",
    "kaw": "kawi",
    "kha": "khasi",
    "kho": "khotanese",
    "kik": "kikuyu",
    "kk": "kazako",
    "kk-lat": "kazako in latino",
    "kky": "guguyimidjir",
    "kl": "groenlandese",
    "km": "khmer",
    "kn": "canarese",
    "ko": "coreano",
    "kok": "konkani",
    "kon": "congolese",
    "kpe": "kpelle",
    "kpg": "kapingamarangi",
    "krl": "careliano",
    "kro": "kru",
    "kru": "kurukh",
    "ks": "kashmiri",
    "ksh": "coloniese",
    "ku": "curdo",
    "kua": "kuanyama",
    "kud": "auhelawa",
    "kus": "kusaie",
    "kut": "kutenai",
    "kw": "cornico",
    "ky": "kirghiso",
    "kv": "komi",
    "la": "latino",
    "lad": "giudeo-spagnolo",
    "lah": "lahnda",
    "lam": "lamba",
    "lb": "lussemburghese",
    "lez": "lezgiano",
    "lg": "luganda",
    "li": "limburghese",
    "lij": "ligure",
    "liv": "livoniano",
    "lld": "ladino",
    "lmo": "lombardo",
    "ln": "lingala",
    "lng": "longobardo",
    "lo": "laotiano",
    "lrc": "luri settentrionale",
    "lt": "lituano",
    "lv": "lettone",
    "mdf": "mokša",
    "mg": "malgascio",
    "mh": "marshallese",
    "mhr": "mari orientale",
    "mi": "maori",
    "min": "menangkabau",
    "mk": "macedone",
    "ml": "malayalam",
    "mn": "mongolo",
    "mnc": "mancese",
    "mo": "moldavo",
    "mov": "mojave",
    "mr": "maratto",
    "ms": "malese",
    "mt": "maltese",
    "mus": "creek",
    "mwl": "mirandese",
    "my": "birmano",
    "myn": "lingue maya",
    "myu": "mundurukú",
    "na": "naurano",
    "nah": "nahuatl",
    "nan": "cinese Min-Nan",
    "nap": "napoletano",
    "nav": "navaho",
    "nb": "bokmål",
    "nci": "nahuatl classico",
    "nch": "nahuatl della Huasteca centrale",
    "nd": "ndebele (nord)",
    "nds": "basso sassone",
    "nds-sass": "basso sassone (secondo Sass)",
    "nds-muen": "basso sassone (ortografia del Münsterland)",
    "ne": "nepalese",
    "new": "newari",
    "ngu": "nahuatl di Guerrero",
    "nhe": "nahuatl della Huasteca orientale",
    "nhn": "nahuatl centrale",
    "nhv": "nahuatl di Temascaltepec",
    "nhw": "nahuatl occidentale",
    "nl": "olandese",
    "nl-vla": "fiammingo",
    "nn": "nynorsk",
    "no": "norvegese",
    "non": "norreno",
    "nov": "novial",
    "nv": "navajo",
    "ny": "chichewa",
    "oc": "occitano",
    "oci": "occitano",
    "odt": "olandese antico",
    "oj": "ojibwa",
    "om": "oromonico",
    "or": "oriya",
    "os": "osseto",
    "pa": "punjabi",
    "pap": "papiamento",
    "pan": "punjabi",
    "pau": "palauano",
    "pcd": "piccardo",
    "pdc": "tedesco della Pennsylvania",
    "phn": "fenicio",
    "pi": "pali",
    "pie": "proto-indoeuropeo",
    "pih": "pitcairnese",
    "pit": "proto-italico",
    "pl": "polacco",
    "pml": "lingua franca",
    "pmm": "pobo",
    "pms": "piemontese",
    "pra": "praghese",
    "prg": "antico prusso",
    "pro": "provenzale antico",
    "ps": "pashto",
    "pt": "portoghese",
    "pt-br": "portoghese del Brasile",
    "pt-pt": "portoghese del Portogallo",
    "qu": "quechua",
    "ra": "romanica",
    "rap": "rapanui",
    "rar": "rarotongan",
    "rgn": "romagnolo",
    "rhg": "rohingya",
    "rm": "romancio",
    "rn": "kirundi",
    "ro": "romeno",
    "roa": "lingue romanze",
    "rom": "romaní",
    "ru": "russo",
    "rw": "ruandese",
    "sa": "sanscrito",
    "sah": "sacha",
    "sc": "sardo",
    "scn": "siciliano",
    "sco": "scozzese",
    "sdc": "sardo sassarese",
    "sdn": "sardo gallurese",
    "se": "lappone settentrionale",
    "sgs": "samogitico",
    "sh": "serbocroato",
    "sjd": "lappone di Kildin",
    "si": "singalese",
    "simple": "simple English",
    "sk": "slovacco",
    "sl": "sloveno",
    "sm": "samoano",
    "smn": "lappone di Inari",
    "sn": "shona",
    "so": "somalo",
    "sov": "sonsorol",
    "sq": "albanese",
    "sr": "serbo",
    "src": "sardo logudorese",
    "srd": "sardo",
    "srn": "sranan",
    "sro": "sardo campidanese",
    "ss": "siswati",
    "st": "sesotho",
    "su": "sudanese",
    "sun": "sundanese",
    "sux": "sumero",
    "sv": "svedese",
    "sw": "swahili",
    "ta": "tamil",
    "te": "telugu",
    "tet": "tetun",
    "tg": "tagico",
    "th": "thailandese",
    "th-ts": "thailandese traslitterato",
    "ti": "tigrino",
    "tk": "turkmeno",
    "tl": "tagalog",
    "tlh": "klingon",
    "tox": "tobiano",
    "tpi": "tok pisin",
    "tpn": "tupì",
    "tr": "turco",
    "trv": "taroko",
    "ts": "tsonga",
    "tsn": "tswana",
    "tt": "tataro",
    "tvl": "tuvalu",
    "tw": "twi",
    "ug": "uiguro",
    "uk": "ucraino",
    "ur": "urdu",
    "uz": "usbeco",
    "ve": "venda",
    "vec": "veneto",
    "vep": "vepso",
    "vi": "vietnamita",
    "vls": "fiammingo",
    "vmf": "francone del Meno",
    "vo": "volapük",
    "vot": "votico",
    "vro": "võro",
    "wa": "vallone",
    "war": "waray",
    "wo": "wolof",
    "xh": "xhosa",
    "xpc": "pecenego",
    "yi": "yiddish",
    "yo": "yoruba",
    "yua": "maya yucateco",
    "yue": "cantonese",
    "za": "zhuang",
    "zea": "zelandese",
    "zh": "cinese",
    "zh-min-nan":"cinese Min-Nan",
    "zh-sc": "cinese semplificato",
    "zh-tc": "cinese tradizionale",
    "zu": "zulu"
}